In [4]:
import torch

In [10]:
tensorX = torch.randn(2, 3, 5, 2)
tensorScaler = torch.randn(1)

In [9]:
tensorX.size()

torch.Size([2, 3, 5, 2])

In [11]:
scaledX = tensorX * tensorScaler

In [12]:
scaledX

tensor([[[[-5.7449e-02,  1.1273e-01],
          [-5.0339e-01, -5.0666e-01],
          [-1.1839e+00, -6.1323e-01],
          [-1.1019e+00, -9.3194e-01],
          [ 8.0318e-01,  9.5669e-04]],

         [[ 5.2625e-01,  1.2777e+00],
          [ 1.4643e-01,  1.9653e-02],
          [-2.4861e-01,  8.9389e-01],
          [ 6.3003e-02,  2.8005e-01],
          [-7.5073e-01, -2.1118e-01]],

         [[-4.0801e-01, -2.3930e-01],
          [ 6.9129e-02, -2.8407e-01],
          [-2.0881e-01,  1.5615e+00],
          [ 7.6224e-02, -9.0168e-01],
          [-8.0034e-01,  3.3752e-01]]],


        [[[ 7.8485e-01, -6.2320e-01],
          [ 1.0279e+00, -5.0961e-02],
          [ 1.5569e+00, -2.5778e-01],
          [-7.2965e-01,  1.9825e-01],
          [ 1.3584e-01,  1.8260e+00]],

         [[ 9.9079e-01,  3.4321e-01],
          [ 1.1563e-01, -6.0578e-02],
          [-1.0557e+00, -7.5676e-01],
          [-8.9520e-01, -3.0323e-01],
          [-3.9833e-01,  1.1552e-01]],

         [[ 1.9142e-01,  6.6616e-01],


In [13]:
tensorScaler

tensor([-0.6003])

In [14]:
 len(scaledX)

2

In [16]:
scaledX.shape

torch.Size([2, 3, 5, 2])

In [17]:
scaledX.reshape((2,5,6))

tensor([[[-5.7449e-02,  1.1273e-01, -5.0339e-01, -5.0666e-01, -1.1839e+00,
          -6.1323e-01],
         [-1.1019e+00, -9.3194e-01,  8.0318e-01,  9.5669e-04,  5.2625e-01,
           1.2777e+00],
         [ 1.4643e-01,  1.9653e-02, -2.4861e-01,  8.9389e-01,  6.3003e-02,
           2.8005e-01],
         [-7.5073e-01, -2.1118e-01, -4.0801e-01, -2.3930e-01,  6.9129e-02,
          -2.8407e-01],
         [-2.0881e-01,  1.5615e+00,  7.6224e-02, -9.0168e-01, -8.0034e-01,
           3.3752e-01]],

        [[ 7.8485e-01, -6.2320e-01,  1.0279e+00, -5.0961e-02,  1.5569e+00,
          -2.5778e-01],
         [-7.2965e-01,  1.9825e-01,  1.3584e-01,  1.8260e+00,  9.9079e-01,
           3.4321e-01],
         [ 1.1563e-01, -6.0578e-02, -1.0557e+00, -7.5676e-01, -8.9520e-01,
          -3.0323e-01],
         [-3.9833e-01,  1.1552e-01,  1.9142e-01,  6.6616e-01,  1.1142e-01,
          -4.8894e-01],
         [-7.9824e-02,  1.3079e-01, -7.3813e-02,  2.4665e-01,  5.5730e-01,
           3.7348e-01]]])

In [18]:
scaledX.reshape((10,6))

tensor([[-5.7449e-02,  1.1273e-01, -5.0339e-01, -5.0666e-01, -1.1839e+00,
         -6.1323e-01],
        [-1.1019e+00, -9.3194e-01,  8.0318e-01,  9.5669e-04,  5.2625e-01,
          1.2777e+00],
        [ 1.4643e-01,  1.9653e-02, -2.4861e-01,  8.9389e-01,  6.3003e-02,
          2.8005e-01],
        [-7.5073e-01, -2.1118e-01, -4.0801e-01, -2.3930e-01,  6.9129e-02,
         -2.8407e-01],
        [-2.0881e-01,  1.5615e+00,  7.6224e-02, -9.0168e-01, -8.0034e-01,
          3.3752e-01],
        [ 7.8485e-01, -6.2320e-01,  1.0279e+00, -5.0961e-02,  1.5569e+00,
         -2.5778e-01],
        [-7.2965e-01,  1.9825e-01,  1.3584e-01,  1.8260e+00,  9.9079e-01,
          3.4321e-01],
        [ 1.1563e-01, -6.0578e-02, -1.0557e+00, -7.5676e-01, -8.9520e-01,
         -3.0323e-01],
        [-3.9833e-01,  1.1552e-01,  1.9142e-01,  6.6616e-01,  1.1142e-01,
         -4.8894e-01],
        [-7.9824e-02,  1.3079e-01, -7.3813e-02,  2.4665e-01,  5.5730e-01,
          3.7348e-01]])

In [20]:
scaledX.mT

tensor([[[[-5.7449e-02, -5.0339e-01, -1.1839e+00, -1.1019e+00,  8.0318e-01],
          [ 1.1273e-01, -5.0666e-01, -6.1323e-01, -9.3194e-01,  9.5669e-04]],

         [[ 5.2625e-01,  1.4643e-01, -2.4861e-01,  6.3003e-02, -7.5073e-01],
          [ 1.2777e+00,  1.9653e-02,  8.9389e-01,  2.8005e-01, -2.1118e-01]],

         [[-4.0801e-01,  6.9129e-02, -2.0881e-01,  7.6224e-02, -8.0034e-01],
          [-2.3930e-01, -2.8407e-01,  1.5615e+00, -9.0168e-01,  3.3752e-01]]],


        [[[ 7.8485e-01,  1.0279e+00,  1.5569e+00, -7.2965e-01,  1.3584e-01],
          [-6.2320e-01, -5.0961e-02, -2.5778e-01,  1.9825e-01,  1.8260e+00]],

         [[ 9.9079e-01,  1.1563e-01, -1.0557e+00, -8.9520e-01, -3.9833e-01],
          [ 3.4321e-01, -6.0578e-02, -7.5676e-01, -3.0323e-01,  1.1552e-01]],

         [[ 1.9142e-01,  1.1142e-01, -7.9824e-02, -7.3813e-02,  5.5730e-01],
          [ 6.6616e-01, -4.8894e-01,  1.3079e-01,  2.4665e-01,  3.7348e-01]]]])

In [21]:
cloned = scaledX.clone()

In [22]:
scaledX += cloned

In [26]:
scaledX

tensor([[[[-1.1490e-01,  2.2546e-01],
          [-1.0068e+00, -1.0133e+00],
          [-2.3678e+00, -1.2265e+00],
          [-2.2038e+00, -1.8639e+00],
          [ 1.6064e+00,  1.9134e-03]],

         [[ 1.0525e+00,  2.5553e+00],
          [ 2.9287e-01,  3.9306e-02],
          [-4.9722e-01,  1.7878e+00],
          [ 1.2601e-01,  5.6011e-01],
          [-1.5015e+00, -4.2236e-01]],

         [[-8.1603e-01, -4.7860e-01],
          [ 1.3826e-01, -5.6815e-01],
          [-4.1763e-01,  3.1231e+00],
          [ 1.5245e-01, -1.8034e+00],
          [-1.6007e+00,  6.7504e-01]]],


        [[[ 1.5697e+00, -1.2464e+00],
          [ 2.0558e+00, -1.0192e-01],
          [ 3.1137e+00, -5.1556e-01],
          [-1.4593e+00,  3.9650e-01],
          [ 2.7168e-01,  3.6521e+00]],

         [[ 1.9816e+00,  6.8641e-01],
          [ 2.3126e-01, -1.2116e-01],
          [-2.1114e+00, -1.5135e+00],
          [-1.7904e+00, -6.0646e-01],
          [-7.9666e-01,  2.3104e-01]],

         [[ 3.8284e-01,  1.3323e+00],


In [28]:
scaledX.reshape((2,5,3,2))

tensor([[[[-1.1490e-01,  2.2546e-01],
          [-1.0068e+00, -1.0133e+00],
          [-2.3678e+00, -1.2265e+00]],

         [[-2.2038e+00, -1.8639e+00],
          [ 1.6064e+00,  1.9134e-03],
          [ 1.0525e+00,  2.5553e+00]],

         [[ 2.9287e-01,  3.9306e-02],
          [-4.9722e-01,  1.7878e+00],
          [ 1.2601e-01,  5.6011e-01]],

         [[-1.5015e+00, -4.2236e-01],
          [-8.1603e-01, -4.7860e-01],
          [ 1.3826e-01, -5.6815e-01]],

         [[-4.1763e-01,  3.1231e+00],
          [ 1.5245e-01, -1.8034e+00],
          [-1.6007e+00,  6.7504e-01]]],


        [[[ 1.5697e+00, -1.2464e+00],
          [ 2.0558e+00, -1.0192e-01],
          [ 3.1137e+00, -5.1556e-01]],

         [[-1.4593e+00,  3.9650e-01],
          [ 2.7168e-01,  3.6521e+00],
          [ 1.9816e+00,  6.8641e-01]],

         [[ 2.3126e-01, -1.2116e-01],
          [-2.1114e+00, -1.5135e+00],
          [-1.7904e+00, -6.0646e-01]],

         [[-7.9666e-01,  2.3104e-01],
          [ 3.8284e-01,  1.3323e

In [29]:
scaledX * cloned

tensor([[[[6.6007e-03, 2.5416e-02],
          [5.0680e-01, 5.1341e-01],
          [2.8033e+00, 7.5211e-01],
          [2.4284e+00, 1.7370e+00],
          [1.2902e+00, 1.8305e-06]],

         [[5.5389e-01, 3.2649e+00],
          [4.2886e-02, 7.7247e-04],
          [1.2361e-01, 1.5981e+00],
          [7.9387e-03, 1.5686e-01],
          [1.1272e+00, 8.9193e-02]],

         [[3.3295e-01, 1.1453e-01],
          [9.5577e-03, 1.6140e-01],
          [8.7206e-02, 4.8768e+00],
          [1.1620e-02, 1.6261e+00],
          [1.2811e+00, 2.2784e-01]]],


        [[[1.2320e+00, 7.7675e-01],
          [2.1132e+00, 5.1940e-03],
          [4.8476e+00, 1.3290e-01],
          [1.0648e+00, 7.8605e-02],
          [3.6906e-02, 6.6688e+00]],

         [[1.9633e+00, 2.3558e-01],
          [2.6740e-02, 7.3394e-03],
          [2.2290e+00, 1.1454e+00],
          [1.6028e+00, 1.8390e-01],
          [3.1733e-01, 2.6690e-02]],

         [[7.3284e-02, 8.8753e-01],
          [2.4829e-02, 4.7813e-01],
          [1.274

In [30]:
scaledX * scaledX

tensor([[[[1.3201e-02, 5.0832e-02],
          [1.0136e+00, 1.0268e+00],
          [5.6067e+00, 1.5042e+00],
          [4.8568e+00, 3.4741e+00],
          [2.5804e+00, 3.6610e-06]],

         [[1.1078e+00, 6.5298e+00],
          [8.5771e-02, 1.5449e-03],
          [2.4723e-01, 3.1962e+00],
          [1.5877e-02, 3.1372e-01],
          [2.2544e+00, 1.7839e-01]],

         [[6.6590e-01, 2.2905e-01],
          [1.9115e-02, 3.2279e-01],
          [1.7441e-01, 9.7536e+00],
          [2.3241e-02, 3.2521e+00],
          [2.5622e+00, 4.5568e-01]]],


        [[[2.4640e+00, 1.5535e+00],
          [4.2264e+00, 1.0388e-02],
          [9.6952e+00, 2.6580e-01],
          [2.1296e+00, 1.5721e-01],
          [7.3811e-02, 1.3338e+01]],

         [[3.9267e+00, 4.7116e-01],
          [5.3479e-02, 1.4679e-02],
          [4.4580e+00, 2.2907e+00],
          [3.2055e+00, 3.6779e-01],
          [6.3467e-01, 5.3380e-02]],

         [[1.4657e-01, 1.7751e+00],
          [4.9658e-02, 9.5626e-01],
          [2.548

In [31]:
scaledX.sum()

tensor(1.6303)

In [32]:
scaledX.sum(axis=0)

tensor([[[ 1.4548, -1.0209],
         [ 1.0491, -1.1152],
         [ 0.7459, -1.7420],
         [-3.6631, -1.4674],
         [ 1.8781,  3.6540]],

        [[ 3.0341,  3.2417],
         [ 0.5241, -0.0819],
         [-2.6086,  0.2743],
         [-1.6644, -0.0463],
         [-2.2981, -0.1913]],

        [[-0.4332,  0.8537],
         [ 0.3611, -1.5460],
         [-0.5773,  3.3847],
         [ 0.0048, -1.3101],
         [-0.4861,  1.4220]]])

In [33]:
scaledX.mean()

tensor(0.0272)

In [36]:
scaledX = scaledX.sum(axis=1, keepdims=True)

In [37]:
scaledX.mean()

tensor(0.0815)

In [41]:
scaledX = scaledX.cumsum(axis = 2)

In [42]:
scaledX.mean()

tensor(0.9266)

In [48]:
scaledX = scaledX.reshape((5,4))

In [45]:
Y = torch.randn(4,5)

In [46]:
Y

tensor([[-1.0348,  0.0772, -0.4825, -0.7511,  1.0009],
        [-1.3462, -0.0985, -0.9835,  0.2232,  2.3964],
        [ 0.8059,  1.3145,  0.4161, -0.4807,  0.6769],
        [-0.1853,  1.8491,  0.9222,  1.1793, -0.6455]])

In [49]:
dotXY = torch.dot(scaledX,Y)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

Dot only works for 1D tensors

In [51]:
a = torch.tensor([1, 4, 65, 34])
b = torch.tensor([2 ,5, 1, 321])

dotProd = torch.dot(a,b)

In [52]:
dotProd

tensor(11001)

In [53]:
scaledX@Y

tensor([[ -3.7319,   0.5912,  -1.8110,   1.5371,   4.8408],
        [ -6.9273,  -5.6964,  -3.6909,   8.0978,   2.2149],
        [  8.2915,   5.8903,   4.2372,   4.7511,  -1.1852],
        [  0.1878,   6.0575,  -1.6812, -11.0287,  11.7724],
        [  1.6565,  11.4010,   4.3743,  -2.2972,   0.5867]])

In [62]:
torch.norm(scaledX)

tensor(17.0108)

In [63]:
torch.abs(scaledX).sum()

tensor(61.6288)